language: r

sudo: required

install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
  - echo 'options(mc.cores = 2)' >> ~/.Rprofile
  
