language: R
cache: packages
sudo: required

before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
  - echo 'options(mc.cores = 2)' >> ~/.Rprofile

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    update: true
    packages:
      - libfreetype6
      - libmagick++-dev
      - cargo
      - libavfilter-dev
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-4'
      - sourceline: 'ppa:jonathonf/ffmpeg-3'

r_github_packages: r-lib/pkgdown

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'
