language: R
cache: packages
sudo: required

before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
  - echo 'options(mc.cores = 2)' >> ~/.Rprofile

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false