language: R
cache: packages
sudo: required

before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
  - echo 'options(mc.cores = 2)' >> ~/.Rprofile

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    update: true
    packages:
      - libfreetype6
      - libmagick++-dev
      - cargo
      - libavfilter-dev
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-4'
      - sourceline: 'ppa:jonathonf/ffmpeg-3'

r_github_packages: r-lib/pkgdown
